//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danos_Veiculo_Comprovativo
    {
        public int IdDanosVeiculoComprovativo { get; set; }
        public int IdDanosVeiculo { get; set; }
        public byte[] Documento { get; set; }
        public string FormatoDocumento { get; set; }
        public string NomeDocumento { get; set; }
        public System.DateTime Data { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Danos_Veiculo Danos_Veiculo { get; set; }
    }
}
