//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danos_Veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Danos_Veiculo()
        {
            this.Danos_Veiculo_Comprovativo = new HashSet<Danos_Veiculo_Comprovativo>();
        }
    
        public int IdDanosVeiculo { get; set; }
        public Nullable<int> IdPedidoMarcacaoHistorico { get; set; }
        public System.DateTime Data { get; set; }
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
        public Nullable<int> IdVeiculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danos_Veiculo_Comprovativo> Danos_Veiculo_Comprovativo { get; set; }
        public virtual Pedido_Marcacao_Historico Pedido_Marcacao_Historico { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
