//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Marcacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido_Marcacao()
        {
            this.Justificacao_Pedido_Marcacao = new HashSet<Justificacao_Pedido_Marcacao>();
            this.Justificacao_Pedido_Marcacao1 = new HashSet<Justificacao_Pedido_Marcacao>();
            this.Pedido_Marcacao_Historico = new HashSet<Pedido_Marcacao_Historico>();
        }
    
        public int IdPedidoMarcacao { get; set; }
        public int IdUtilizador { get; set; }
        public System.DateTime DataPedido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Justificacao_Pedido_Marcacao> Justificacao_Pedido_Marcacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Justificacao_Pedido_Marcacao> Justificacao_Pedido_Marcacao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Marcacao_Historico> Pedido_Marcacao_Historico { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
