//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil_Permissao
    {
        public int IdPerfilPermissao { get; set; }
        public int IdPerfil { get; set; }
        public int IdPermissao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Permissao Permissao { get; set; }
    }
}
