//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo_Entrega
    {
        public int IdVeiculoEntrega { get; set; }
        public int IdPedidoMarcacaoHistorico { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Kms { get; set; }
    
        public virtual Pedido_Marcacao_Historico Pedido_Marcacao_Historico { get; set; }
    }
}
